---
title: '`r paste("Survival analysis from ",ifile)`'
output:
  html_document:
    theme: default
    toc: yes
  pdf_document:
    highlight: zenburn
    toc: yes
date: '`r paste("Generated on ", format(Sys.time(), "%a %b %d %X %Y"))`'
---

Overview
-----------------------------------

Response: **`r objres$Resp`**

Analysis type: **`r objres$Typ`**

Parameters: **`r objres$Par`**

```{r table0, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
require(pander)
sumIds=sumIdKM(objres)
    rownames(sumIds)=NULL
panderOptions('table.split.table', Inf)
    pander(sumIds)
```
Num. of animals: **`r nrow(objres$Df)`**, num. of events: **`r sum(objres$Df$Event)`**


```{r plot1, fig.height=5,fig.width=8,echo=FALSE}
par(mar = c(4, 4, 1, 1))
lwd=ifelse(exists(input$kmlwd),as.numeric(input$kmlwd),2)
cexpt=ifelse(exists(input$kmcexpt),as.numeric(input$kmcexpt),1.5)
exportKM(p1,dogrps=FALSE,lwd=lwd,cexpt=cexpt)
```

\clearpage

Stats
-----------------------------------

**ANOVA**
```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
if(!is.null(modKM$modTab)) pander(modKM$modTab)
```

**Hazard ratios**

P-value adjustement: **`r pvadj`**

```{r table3, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
if(!is.null(modKM$hrTab)) pander(modKM$hrTab)
```

Modelling
-----------------------------------

**Cox regression**
```{r model, results='markdown',echo=FALSE}
if(!is.null(modKM$model)) modKM$model
```

\clearpage

Data
-----------------------------------
```{r table1, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
require(pander)
panderOptions('table.split.table', Inf)
dat=objres$Df[,1:5,drop=FALSE]
rownames(dat)=NULL
pander(dat)
```

