---
title: '`r paste("Cross-sectional analysis from ",ifile)`'
output:
  html_document:
    theme: default
    toc: yes
  pdf_document:
    highlight: zenburn
    toc: yes
date: '`r paste("Generated on ", format(Sys.time(), "%a %b %d %X %Y"))`'
---

Overview
-----------------------------------

Response: **`r objres$Resp`**

Transformation: **`r objres$Trans`**

Analysis type: **`r objres$Par`**

Design for modelling (the sampling day given in parenthesis if different between animals): 
```{r table1, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
require(pander)
v=objres$Df$Id
if(grepl("range",objres$Par)) v=paste(objres$Df$Id," (",objres$Df$Tp,")",sep="")
names(v)=NULL
lso=order(-objres$Df$Tp)
v=tapply(v[lso],objres$Df$Grp[lso],sort)
nnamis=tapply(v[lso],objres$Df$Grp[lso],length)
ltps=tapply(objres$Df$Tp[lso],objres$Df$Grp[lso],function(x){
  itp=range(x)
  if(itp[1]==itp[2]) return(as.character(itp[1]))
  paste(itp,collapse='-')
})
sumIds=data.frame(cbind(Group=names(v),N=nnamis,Tp=ltps,Animals=unlist(sapply(v,paste,collapse=" "))))
rownames(sumIds)=NULL
panderOptions('table.split.table', Inf)
pander(sumIds)
```

```{r outl, message=FALSE,echo=FALSE}
louts='no outliers'
if(any(csres$data$out)){
  cdat=csres$data[csres$data$out,]
  louts=unname(tapply(1:nrow(cdat),factor(cdat$Id),function(x) 
    paste("Id=",cdat$Id[x[1]],"(",cdat$Grp[x[1]],"): ",paste(cdat$Tp[x],collapse=","),sep="")))
}
anim=sum(!csres$data$out)
```

Outliers: **`r louts`**

Num. of animals: **`r anim`**

```{r plot1, fig.height=4,fig.width=6,echo=FALSE}
par(mar = c(4, 4, 1, 1))
cexpt=ifelse(exists('input$cscexpt'),as.numeric(input$cscexpt),1.2)
exportCS(retplotcs,dogrps=FALSE,cexpt=cexpt,strict=FALSE)
```

\clearpage

Stats
-----------------------------------

**ANOVA**
```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
pander(csres$AnovaTab)
```

**Selected pairwise comparisons**

P-value adjustement: **`r pvadj`**

```{r table3, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
pander(formatpw)
```

\clearpage

Model
-----------------------------------
```{r model, results='markdown',echo=FALSE}
summary(csres$mod)
```

**All pairwise comparisons**
```{r table4, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
pander(csres$pairTab)
```


\clearpage

QQ-plot
-----------------------------------

```{r plot, fig.height=4,echo=FALSE}
par(mar = c(4, 4, 1, 1))
    tmpqqp=diagdata$data[,c("resid","qt","Tp"  ,"Grp","Id","color")]
    names(tmpqqp)[1:3]=c("x","y","Tp")
    limxqq=diagdata$limxqq
    ab=c(range(limxqq),range(limxqq))
    plot(range(limxqq),range(limxqq),cex=0,
    xlab="Pearson residuals",xlim=range(limxqq),
    ylab="Quantile",ylim=range(limxqq),axes=F)
    axis(1,at=limxqq);axis(2,at=limxqq,las=2)
    abline(0,1)
    points(tmpqqp$x,tmpqqp$y,col=tmpqqp$color,pch=16)
```




Residuals vs grp
-----------------------------------

```{r plot2, fig.height=4,fig.width=6,echo=FALSE}
par(mar = c(4, 4, 1, 1))
tmpbxp=diagdata$data[,c("Id","resid","Grp","color")]
limxqq=diagdata$limxqq
re=boxplot(resid~Grp,tmpbxp,axes=F,cex=0,ylab="Pearson residuals",ylim=range(limxqq))
abline(h=0)
axis(2,at=limxqq,las=2)
for(i in 1:length(re$n)) axis(1,at=i,paste(re$name[i],"\n(",re$n[i],")",sep=""),
                              tick=F,cex.axis=ifelse(length(re$names)>5,0.6,1))
beeswarm(resid~Grp,tmpbxp,add=T,pwcol=tmpbxp$color,pch=16)
```


Residuals (transformed data) vs fit
-----------------------------------

```{r plot3, fig.height=4,echo=FALSE}
par(mar = c(4, 4, 1, 1))
    tmpresf=diagdata$data[,c("resid","Fit" ,"Tp" ,"Grp","Id","color")]
    names(tmpresf)[1:2]=c("y","x")
    limxqq=diagdata$limxqq
    limyfit=pretty(tmpresf$x)
  
     plot(range(limxqq),range(limxqq),cex=0,
    xlab="Fitted",xlim=range(limyfit),
    ylab="Pearson residuals",ylim=range(limxqq),axes=F)
     abline(h=0)
    axis(1,at=limyfit);axis(2,at=limxqq,las=2)
    points(tmpresf$x,tmpresf$y,col=tmpresf$color,pch=16)
```


\clearpage

Data
-----------------------------------
```{r table5, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
require(pander)
panderOptions('table.split.table', Inf)
dat=csres$data[,c( "Tp","Id","Resp","Resp_ori", "Grp" ,"out"  )]
dat=dat[order(dat$Grp,dat$Id),]
rownames(dat)=NULL
pander(dat)
```
