---
title: '`r paste("Cross-sectional analysis from ",ifile)`'
output:
html_document:
theme: default
toc: yes
pdf_document:
highlight: zenburn
date: '`r paste("Compiled on ", format(Sys.time(), "%a %b %d %X %Y"))`'
---

Overview
-----------------------------------

Response: **`r objres$Resp`**

Analysis type: **`r objres$Par`**

Design for modelling (the sampling day given in parenthesis if different between animals): 
```{r table1, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
require(pander)
v=objres$Df$Id
if(grepl("range",objres$Par)) v=paste(objres$Df$Id," (",objres$Df$Tp,")",sep="")
names(v)=NULL
lso=order(-objres$Df$Tp)
v=tapply(v[lso],objres$Df$Grp[lso],sort)
sumIds=data.frame(cbind(Group=names(v),Animals=unlist(sapply(v,paste,collapse=" "))))
rownames(sumIds)=NULL
panderOptions('table.split.table', Inf)
pander(sumIds)
```

```{r outl, message=FALSE,echo=FALSE}
louts='no outliers'
if(any(mod$data$out)){
  cdat=mod$data[mod$data$out,]
  louts=unname(tapply(1:nrow(cdat),factor(cdat$Id),function(x) 
    paste("Id=",cdat$Id[x[1]],"(",cdat$Grp[x[1]],"): ",paste(cdat$Tp[x],collapse=","),sep="")))
}
anim=sum(!mod$data$out)
```

Outliers: **`r louts`**

Num. of animals: **`r anim`**

```{r plot1, fig.height=5,fig.width=6,echo=FALSE}
par(mar = c(4, 4, 1, 1))
cexpt=ifelse(exists(input$cscexpt),as.numeric(input$cscexpt),1.2)
exportCS(p2,dogrps=F,cexpt=cexpt)
```


Stats
-----------------------------------

**ANOVA**
```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
pander(mod$AnovaTab)
```

**Selected pairwise comparisons**
```{r table3, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
pander(formatpw)
```

\clearpage

Model
-----------------------------------
```{r model, results='markdown',echo=FALSE}
mod$mod
```

**All pairwise comparisons**
```{r table4, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
pander(mod$pairTab)
```


\clearpage

QQ-plot
-----------------------------------

```{r plot, fig.height=4,echo=FALSE}
par(mar = c(4, 4, 1, 1))

    tmpqqp=plotdata$data[,c("resid","qt","x"  ,"Grp","Id","color")]
    names(tmpqqp)[1:3]=c("x","y","Tp")
    ab=c(range(plotdata$limxqq),range(plotdata$limxqq))
    plot(range(plotdata$limxqq),range(plotdata$limxqq),cex=0,
    xlab="Pearson residuals",xlim=range(plotdata$limxqq),
    ylab="Quantile",ylim=range(plotdata$limxqq),axes=F)
    axis(1,at=plotdata$limxqq);axis(2,at=plotdata$limxqq,las=2)
    abline(0,1)
    points(tmpqqp$x,tmpqqp$y,col=tmpqqp$color,pch=16)
```




Residuals vs grp
-----------------------------------

```{r plot2, fig.height=4,fig.width=6,echo=FALSE}
par(mar = c(4, 4, 1, 1))
     tmpbxp=plotdata$data[,c("Id","resid","Grp","color")]
    names(tmpbxp)[2]="x"
  re=boxplot(x~Grp,tmpbxp,axes=F,cex=0,ylab="Pearson residuals",ylim=range(plotdata$limxqq))
  abline(h=0)
   axis(2,at=plotdata$limxqq,las=2)
   for(i in 1:length(re$n)) axis(1,at=i,re$name[i],las=2,tick=F,cex.axis=ifelse(length(re$names)>5,0.6,1))
  beeswarm(x~Grp,tmpbxp,add=T,pwcol=tmpbxp$color,pch=16)
```


Residuals vs fit
-----------------------------------

```{r plot3, fig.height=4,echo=FALSE}
par(mar = c(4, 4, 1, 1))
  tmpresf=plotdata$data[,c("resid","fit" ,"x" ,"Grp","Id","color")]
  names(tmpresf)[1:3]=c("y","x","Tp")
  
     plot(range(plotdata$limxqq),range(plotdata$limxqq),cex=0,
    xlab="Fitted",xlim=range(plotdata$limyfit0),
    ylab="Pearson residuals",ylim=range(plotdata$limxqq),axes=F)
     abline(h=0)
    axis(1,at=plotdata$limyfit0);axis(2,at=plotdata$limxqq,las=2)
    points(tmpresf$x,tmpresf$y,col=tmpresf$color,pch=16)
```


\clearpage

Data
-----------------------------------
```{r table0, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
require(pander)
panderOptions('table.split.table', Inf)
dat=mod$data[,c( "Tp","Id","Resp", "Grp" ,"out"  )]
rownames(dat)=NULL
dat=dat[order(dat$Grp,dat$Id),]
pander(dat)
```
